// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminBack.Models;

public partial class AccesoUsuario
{
    public int Id { get; set; }

    public int? IdSubModulo { get; set; }

    public int? IdRol { get; set; }

    public bool? Activo { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public virtual Rol IdRolNavigation { get; set; }

    public virtual SubModuloAdmin IdSubModuloNavigation { get; set; }
}