// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminBack.Models;

public partial class SubModuloAdmin
{
    public int IdSubModulo { get; set; }

    public int? IdModulo { get; set; }

    public string Nombre { get; set; }

    public bool? Activo { get; set; }

    public string Icono { get; set; }

    public string Ruta { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public virtual ICollection<AccesoUsuario> AccesoUsuarios { get; set; } = new List<AccesoUsuario>();

    public virtual ModuloAdmin IdModuloNavigation { get; set; }
}