// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminBack.Models;

public partial class Usuario
{
    public int IdUsuario { get; set; }

    public string Correo { get; set; }

    public string Usuario1 { get; set; }

    public bool? Activo { get; set; }

    public int? IdRol { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public virtual Rol IdRolNavigation { get; set; }

    public virtual Sesion Sesion { get; set; }
}